require 'rubygems'
require 'fileutils'
require File.join(File.dirname(File.expand_path(__FILE__)), '../lib/sequel/annotate')

ENV['MT_NO_PLUGINS'] = '1' # Work around stupid autoloading of plugins
gem 'minitest'
require 'minitest/autorun'

DB = Sequel.connect(ENV['SEQUEL_ANNOTATE_SPEC_POSTGRES_URL'] || 'postgres:///sequel_annotate_test?user=sequel_annotate&password=sequel_annotate')
raise "test database name doesn't end with test" unless DB.get{current_database.function} =~ /test\z/
if defined?(JRUBY_VERSION)
  SDB = Sequel.connect('jdbc:sqlite::memory:')
else
  SDB = Sequel.sqlite
end

DB.drop_function(:valid_price) rescue nil
[DB, SDB].each do |db|
  db.drop_table?(:newline_tests, :items, :manufacturers, :categories)

  db.create_table :categories do
    primary_key :id
    String :name, :index=>{:unique=>true, :name=>'categories_name_key'}, :null=>false
  end

  db.create_table :manufacturers do
    String :name
    String :location
    primary_key [:name, :location]
  end

  db.create_table :items do
    primary_key :id
    foreign_key :category_id, :categories, :null => false
    foreign_key [:manufacturer_name, :manufacturer_location], :manufacturers

    String :manufacturer_name, :size => 50
    String :manufacturer_location
    TrueClass :in_stock, :default => false
    String :name, :default => "John"
    Float  :price, :default => 0

    constraint :pos_id, Sequel.expr(:id) > 0

    index [:manufacturer_name, :manufacturer_location], :name=>:name, :unique=>true
    index [:manufacturer_name], :name=>:manufacturer_name
  end

  db.create_table :newline_tests do
    Integer :abcde_fghi_id
    Integer :jkl_mnopqr_id
    constraint(:valid_stuvw_xyz0, Sequel.case({{:abcde_fghi_id=>[5,6]}=>Sequel.~(:jkl_mnopqr_id=>nil)}, :jkl_mnopqr_id=>nil))
  end
end

DB.run <<SQL
CREATE FUNCTION valid_price() RETURNS trigger AS $emp_stamp$
    BEGIN
        -- Check that empname and salary are given
        IF NEW.price > 1000000 THEN
            RAISE EXCEPTION 'price is too high';
        END IF;
        RETURN NEW;
    END;
$emp_stamp$ LANGUAGE plpgsql;
SQL

DB.run <<SQL
CREATE TRIGGER valid_price BEFORE INSERT OR UPDATE ON items
    FOR EACH ROW EXECUTE PROCEDURE valid_price();
SQL

Minitest.after_run do
  DB.drop_table(:items, :manufacturers, :categories)
  DB.drop_function(:valid_price)
end

class ::Item < Sequel::Model; end
class ::Category < Sequel::Model; end
class ::Manufacturer < Sequel::Model; end
class ::SItem < Sequel::Model(SDB[:items]); end
class ::SCategory < Sequel::Model(SDB[:categories]); end
class ::SManufacturer < Sequel::Model(SDB[:manufacturers]); end
class ::NewlineTest < Sequel::Model; end

# Abstract Base Class
ABC = Class.new(Sequel::Model)

module ModelNamespace
  Model = Class.new(Sequel::Model)
  Model.def_Model(self)
  class Itms < Model(:items); end
end

describe Sequel::Annotate do
  def fix_pg_comment(comment)
    if DB.server_version >= 100002 && (Sequel::MAJOR > 5 || (Sequel::MAJOR == 5 && Sequel::MINOR >= 7))
      comment = comment.sub(/DEFAULT nextval\('[a-z]+_id_seq'::regclass\)/, 'GENERATED BY DEFAULT AS IDENTITY')
    end
    comment
  end

  before do
    Dir.mkdir('spec/tmp') unless File.directory?('spec/tmp')
  end
  after do
    Dir['spec/tmp/*.rb'].each{|f| File.delete(f)}
  end

  it "#schema_info should return the model schema comment" do
    Sequel::Annotate.new(Item).schema_comment.must_equal(fix_pg_comment((<<OUTPUT).chomp))
# Table: items
# Columns:
#  id                    | integer               | PRIMARY KEY DEFAULT nextval('items_id_seq'::regclass)
#  category_id           | integer               | NOT NULL
#  manufacturer_name     | character varying(50) |
#  manufacturer_location | text                  |
#  in_stock              | boolean               | DEFAULT false
#  name                  | text                  | DEFAULT 'John'::text
#  price                 | double precision      | DEFAULT 0
# Indexes:
#  items_pkey        | PRIMARY KEY btree (id)
#  name              | UNIQUE btree (manufacturer_name, manufacturer_location)
#  manufacturer_name | btree (manufacturer_name)
# Check constraints:
#  pos_id | (id > 0)
# Foreign key constraints:
#  items_category_id_fkey       | (category_id) REFERENCES categories(id)
#  items_manufacturer_name_fkey | (manufacturer_name, manufacturer_location) REFERENCES manufacturers(name, location)
# Triggers:
#  valid_price | BEFORE INSERT OR UPDATE ON items FOR EACH ROW EXECUTE PROCEDURE valid_price()
OUTPUT

    Sequel::Annotate.new(Category).schema_comment.must_equal(fix_pg_comment((<<OUTPUT).chomp))
# Table: categories
# Columns:
#  id   | integer | PRIMARY KEY DEFAULT nextval('categories_id_seq'::regclass)
#  name | text    | NOT NULL
# Indexes:
#  categories_pkey     | PRIMARY KEY btree (id)
#  categories_name_key | UNIQUE btree (name)
# Referenced By:
#  items | items_category_id_fkey | (category_id) REFERENCES categories(id)
OUTPUT

    Sequel::Annotate.new(Manufacturer).schema_comment.must_equal((<<OUTPUT).chomp)
# Table: manufacturers
# Primary Key: (name, location)
# Columns:
#  name     | text |
#  location | text |
# Indexes:
#  manufacturers_pkey | PRIMARY KEY btree (name, location)
# Referenced By:
#  items | items_manufacturer_name_fkey | (manufacturer_name, manufacturer_location) REFERENCES manufacturers(name, location)
OUTPUT

    Sequel::Annotate.new(NewlineTest).schema_comment.must_equal((<<OUTPUT).chomp)
# Table: newline_tests
# Columns:
#  abcde_fghi_id | integer |
#  jkl_mnopqr_id | integer |
# Check constraints:
#  valid_stuvw_xyz0 | (
#    CASE
#        WHEN abcde_fghi_id = ANY (ARRAY[5, 6]) THEN jkl_mnopqr_id IS NOT NULL
#        ELSE jkl_mnopqr_id IS NULL
#    END)
OUTPUT

    Sequel::Annotate.new(SItem).schema_comment.must_equal((<<OUTPUT).chomp)
# Table: items
# Columns:
#  id                    | integer          | PRIMARY KEY AUTOINCREMENT
#  category_id           | integer          | NOT NULL
#  manufacturer_name     | varchar(50)      |
#  manufacturer_location | varchar(255)     |
#  in_stock              | boolean          | DEFAULT 0
#  name                  | varchar(255)     | DEFAULT 'John'
#  price                 | double precision | DEFAULT 0
# Indexes:
#  manufacturer_name | (manufacturer_name)
#  name              | UNIQUE (manufacturer_name, manufacturer_location)
# Foreign key constraints:
#  (category_id) REFERENCES categories
#  (manufacturer_name, manufacturer_location) REFERENCES manufacturers
OUTPUT

    Sequel::Annotate.new(SCategory).schema_comment.must_equal((<<OUTPUT).chomp)
# Table: categories
# Columns:
#  id   | integer      | PRIMARY KEY AUTOINCREMENT
#  name | varchar(255) | NOT NULL
# Indexes:
#  categories_name_key | UNIQUE (name)
OUTPUT

    Sequel::Annotate.new(SManufacturer).schema_comment.must_equal((<<OUTPUT).chomp)
# Table: manufacturers
# Primary Key: (name, location)
# Columns:
#  name     | varchar(255) |
#  location | varchar(255) |
OUTPUT
  end
  
  [['without options', 'after', []], ['with :position=>:before option', 'before', [{:position=>:before}]]].each do |desc, pos, args|
    it "#annotate #{desc} should annotate the file comment" do
      FileUtils.cp(Dir['spec/unannotated/*.rb'], 'spec/tmp')

      [Item, Category, Manufacturer, SItem, SCategory, SManufacturer].each do |model|
        filename = model.name.downcase
        2.times do
          Sequel::Annotate.new(model).annotate("spec/tmp/#{filename}.rb", *args)
          expected = File.read("spec/annotated_#{pos}/#{filename}.rb")
          expected = fix_pg_comment(expected) if model.db == DB
          File.read("spec/tmp/#{filename}.rb").must_equal expected
        end
      end
    end

    it ".annotate #{desc} should annotate all files given" do
      FileUtils.cp(Dir['spec/unannotated/*.rb'], 'spec/tmp')

      2.times do
        Sequel::Annotate.annotate(Dir["spec/tmp/*.rb"], *args)
        [Item, Category, Manufacturer, SItem, SCategory, SManufacturer].each do |model|
          filename = model.name.downcase
          expected = File.read("spec/annotated_#{pos}/#{filename}.rb")
          expected = fix_pg_comment(expected) if model.db == DB
          File.read("spec/tmp/#{filename}.rb").must_equal expected
        end
      end
    end
  end

  it ".annotate #{desc} should handle :namespace option" do
    FileUtils.cp('spec/namespaced/itm_unannotated.rb', 'spec/tmp/')
    Sequel::Annotate.annotate(["spec/tmp/itm_unannotated.rb"], :namespace=>'ModelNamespace')
    File.read("spec/tmp/itm_unannotated.rb").must_equal fix_pg_comment(File.read('spec/namespaced/itm_annotated.rb'))
  end
end
